### ISSUE TITLE
hub-mirror-action 用于在 GitHub 和 Gitee 之间同步代码的 GitHub Action

### ISSUE THREAD

**Issue by liuvigongzuoshi** [liuvigongzuoshi/web-developer-resources#117]
# [Hub Mirror Action ](https://github.com/Yikun/hub-mirror-action)

一个 GitHub Action，用于在 GitHub 和 Gitee 之间同步代码

```
steps:
- name: Mirror the Github organization repos to Gitee.
  uses: Yikun/hub-mirror-action@master
  with:
    src: github/kunpengcompute
    dst: gitee/kunpengcompute
    dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    dst_token: ${{ secrets.GITEE_TOKEN }}
    account_type: org
```
